site_name: My Docs
repo_url: https://github.com/mpizenberg/Singapore_interview
site_description: A quick repository for my interview for an internship in Singapore
site_author: Matthieu Pizenberg

site_dir: ../../Singapore_interview_gh-pages

pages:
    - ['index.md', 'Introduction']
    - ['install.md', 'Installation']
    - ['extraction.md', 'Frame extraction']
    - ['superpixel.md', 'Superpixels segmentation']
    - ['box.md', 'Boundary box']
    - ['doc.md', 'Building this documentation']

theme: readthedocs
